### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by luxiangze** [wuzeyou/alipay2moneywiz#1]
请问一下，下边报错是什么原因？
if (recordStr.includes(k)) {
                  ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at mapAccount (file:///C:/Users/gyong/OneDrive/%E6%A1%8C%E9%9D%A2/%E5%AF%B9%E8%B4%A6%EF%BC%8822.11.1-23.02.01%EF%BC%89/alipay2moneywiz-master/alipay.js:123:19)
    at file:///C:/Users/gyong/OneDrive/%E6%A1%8C%E9%9D%A2/%E5%AF%B9%E8%B4%A6%EF%BC%8822.11.1-23.02.01%EF%BC%89/alipay2moneywiz-master/alipay.js:69:25
    at Array.forEach (<anonymous>)
    at mainProcess (file:///C:/Users/gyong/OneDrive/%E6%A1%8C%E9%9D%A2/%E5%AF%B9%E8%B4%A6%EF%BC%8822.11.1-23.02.01%EF%BC%89/alipay2moneywiz-master/alipay.js:62:11)

**Comment by wuzeyou** [comment]
支付宝账单的格式变动了，我稍后提交修复

**Comment by wuzeyou** [comment]
fixed
